1. Drive Connect

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Imports

In [ ]:
import os

os.path.exists('/content/drive')

False

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

EXPORT REPORT TO EXCEL

In [ ]:
# ===== EXPORT REPORT TO EXCEL =====

output_path = "/content/drive/MyDrive/GColab/final_report.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)

    if "Category" in df.columns and "Amount" in df.columns:
        category_summary = df.groupby("Category")["Amount"].sum().reset_index()
        category_summary.to_excel(writer, sheet_name="Category_Summary", index=False)

print("✅ Report saved to:", output_path)

✅ Report saved to: /content/drive/MyDrive/GColab/final_report.xlsx

In [ ]:
import os

try:
    os.listdir('/content/drive/MyDrive')
    print("✅ Drive already connected")
except Exception as e:
    print("⚠️ Reconnecting Drive...")
    from google.colab import drive
    drive.mount('/content/drive')

✅ Drive already connected

IMPORTS

In [ ]:
import pandas as pd

In [ ]:
temp_df = pd.read_excel(file_path)

In [ ]:
import plotly.express as px

In [ ]:
import os

folder_path = "/content/drive/MyDrive/GColab"
print(os.listdir(folder_path))

['sample_file_3.xlsx', 'sample_file_2.xlsx', 'sample_file_1.xlsx', 'sample_colab_excel.xlsx', 'final_report.xlsx', 'report_summary.txt']

FOLDER PATH

In [ ]:
folder_path = "/content/drive/MyDrive/GColab"

all_files = [
    f for f in os.listdir(folder_path)
    if f.endswith(".xlsx")
    and not f.startswith("final")
    and not f.startswith("sample_colab")
]

print("Files found:")
for f in all_files:
    print("-", f)

Files found:
- sample_file_3.xlsx
- sample_file_2.xlsx
- sample_file_1.xlsx

In [ ]:
dataframes = []

for file in all_files:
    file_path = os.path.join(folder_path, file)
    temp_df = pd.read_excel(file_path)
    temp_df["Source_File"] = file
    dataframes.append(temp_df)

combined_df = pd.concat(dataframes, ignore_index=True)

print("\nCombined shape before cleaning:", combined_df.shape)

NameError: name 'pd' is not defined

In [ ]:
folder_path = "/content/drive/MyDrive/GColab"

all_files = [
    f for f in os.listdir(folder_path)
    if f.endswith(".xlsx")
    and not f.startswith("final")
    and not f.startswith("sample_colab")
]

print("Files found:")
for f in all_files:
    print("-", f)

Files found:
- sample_file_3.xlsx
- sample_file_2.xlsx
- sample_file_1.xlsx

In [ ]:
dataframes = []

for file in all_files:
    file_path = os.path.join(folder_path, file)
    temp_df = pd.read_excel(file_path)
    temp_df["Source_File"] = file
    dataframes.append(temp_df)

combined_df = pd.concat(dataframes, ignore_index=True)

print("\nCombined shape before cleaning:", combined_df.shape)

Combined shape before cleaning: (30, 5)

SUMMARY

In [ ]:
combined_df = combined_df.dropna(how="all")
combined_df = combined_df.drop_duplicates()

print("Combined shape after cleaning:", combined_df.shape)

combined_df.head()

Combined shape after cleaning: (30, 5)

    Name  Amount    Category        Date         Source_File
0  Rohit    2927  Operations  2026-01-01  sample_file_3.xlsx
1  Rohit    2015  Operations  2026-01-02  sample_file_3.xlsx
2  Priya    2879       Sales  2026-01-03  sample_file_3.xlsx
3  Vikas     553   Marketing  2026-01-04  sample_file_3.xlsx
4   Neha    2756       Sales  2026-01-05  sample_file_3.xlsx

In [ ]:
print("\n===== SUMMARY =====")
print("Rows:", len(combined_df))
print("Columns:", list(combined_df.columns))

if "Amount" in combined_df.columns:
    print("\nTotal Amount:", combined_df["Amount"].sum())
    print("Average Amount:", combined_df["Amount"].mean())
    print("Max Amount:", combined_df["Amount"].max())
    print("Min Amount:", combined_df["Amount"].min())

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)
    print("\nCategory Summary:")
    print(category_summary)

===== SUMMARY =====
Rows: 30
Columns: ['Name', 'Amount', 'Category', 'Date', 'Source_File']

Total Amount: 57846
Average Amount: 1928.2
Max Amount: 2988
Min Amount: 553

Category Summary:
Category
Sales         24345
Operations    20120
Marketing     13381
Name: Amount, dtype: int64

In [ ]:
category_summary = combined_df.groupby("Category")["Amount"].sum().reset_index()

fig = px.bar(
    category_summary,
    x="Category",
    y="Amount",
    title="Combined Category-wise Total Amount",
    text="Amount"
)
fig.show()

fig2 = px.pie(
    category_summary,
    names="Category",
    values="Amount",
    title="Combined Category Contribution"
)
fig2.show()

In [ ]:
output_path = "/content/drive/MyDrive/GColab/final_multi_file_report.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    combined_df.to_excel(writer, sheet_name="Combined_Data", index=False)

    source_summary = combined_df["Source_File"].value_counts().reset_index()
    source_summary.columns = ["Source_File", "Row_Count"]
    source_summary.to_excel(writer, sheet_name="Source_Summary", index=False)

    category_summary.to_excel(writer, sheet_name="Category_Summary", index=False)

print("✅ Saved report:", output_path)

✅ Saved report: /content/drive/MyDrive/GColab/final_multi_file_report.xlsx

In [ ]:
source_summary = combined_df.groupby("Source_File")["Amount"].sum().reset_index()
source_summary

          Source_File  Amount
0  sample_file_1.xlsx   19063
1  sample_file_2.xlsx   17923
2  sample_file_3.xlsx   20860

In [ ]:
import plotly.express as px

fig = px.bar(
    source_summary,
    x="Source_File",
    y="Amount",
    title="Source-wise Total Amount",
    text="Amount"
)
fig.show()

Date-wise trend (NEW 👇)

In [ ]:
combined_df["Date"] = pd.to_datetime(combined_df["Date"])

date_summary = combined_df.groupby("Date")["Amount"].sum().reset_index()
date_summary

        Date  Amount
0 2026-01-01    6633
1 2026-01-02    4189
2 2026-01-03    6843
3 2026-01-04    4897
4 2026-01-05    4520
5 2026-01-06    7999
6 2026-01-07    6363
7 2026-01-08    5017
8 2026-01-09    5671
9 2026-01-10    5714

In [ ]:
fig = px.line(
    date_summary,
    x="Date",
    y="Amount",
    title="Date-wise Amount Trend"
)
fig.show()

Export

In [ ]:
# Export final report

Auto insights

In [ ]:
print("===== AUTO INSIGHTS =====")

if "Amount" in combined_df.columns:
    total_amount = combined_df["Amount"].sum()
    avg_amount = combined_df["Amount"].mean()
    max_amount = combined_df["Amount"].max()
    min_amount = combined_df["Amount"].min()

    print(f"Total amount is {total_amount}")
    print(f"Average amount is {avg_amount:.2f}")
    print(f"Highest amount is {max_amount}")
    print(f"Lowest amount is {min_amount}")

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

    print("\nCategory-wise total:")
    print(category_summary)

    top_category = category_summary.idxmax()
    top_value = category_summary.max()

    low_category = category_summary.idxmin()
    low_value = category_summary.min()

    print(f"\nTop category is {top_category} with total {top_value}")
    print(f"Lowest category is {low_category} with total {low_value}")

if "Amount" in combined_df.columns:
    top_row = combined_df.loc[combined_df["Amount"].idxmax()]
    print("\nTop row:")
    print(top_row)

print("\n===== INSIGHTS COMPLETE =====")

===== AUTO INSIGHTS =====
Total amount is 57846
Average amount is 1928.20
Highest amount is 2988
Lowest amount is 553

Category-wise total:
Category
Sales         24345
Operations    20120
Marketing     13381
Name: Amount, dtype: int64

Top category is Sales with total 24345
Lowest category is Marketing with total 13381

Top row:
Name                         Priya
Amount                        2988
Category                     Sales
Date           2026-01-06 00:00:00
Source_File     sample_file_1.xlsx
Name: 25, dtype: object

===== INSIGHTS COMPLETE =====

Human-style summary

In [ ]:
if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

    top_category = category_summary.idxmax()
    top_value = category_summary.max()

    low_category = category_summary.idxmin()
    low_value = category_summary.min()

    total_amount = combined_df["Amount"].sum()
    avg_amount = combined_df["Amount"].mean()

    print("===== HUMAN STYLE SUMMARY =====")
    print(f"The dataset contains {len(combined_df)} cleaned records.")
    print(f"The total amount across all records is {total_amount}.")
    print(f"The average amount per record is {avg_amount:.2f}.")
    print(f"The strongest category is {top_category}, contributing {top_value}.")
    print(f"The weakest category is {low_category}, contributing {low_value}.")
    print("This indicates where the data is currently strongest and which category may need more attention.")

===== HUMAN STYLE SUMMARY =====
The dataset contains 30 cleaned records.
The total amount across all records is 57846.
The average amount per record is 1928.20.
The strongest category is Sales, contributing 24345.
The weakest category is Marketing, contributing 13381.
This indicates where the data is currently strongest and which category may need more attention.

Source-wise insights

In [ ]:
if "Source_File" in combined_df.columns and "Amount" in combined_df.columns:
    source_summary = combined_df.groupby("Source_File")["Amount"].sum().sort_values(ascending=False)

    top_source = source_summary.idxmax()
    top_source_value = source_summary.max()

    print("===== SOURCE INSIGHTS =====")
    print(source_summary)
    print(f"\nTop source file is {top_source} with total amount {top_source_value}.")

===== SOURCE INSIGHTS =====
Source_File
sample_file_3.xlsx    20860
sample_file_1.xlsx    19063
sample_file_2.xlsx    17923
Name: Amount, dtype: int64

Top source file is sample_file_3.xlsx with total amount 20860.

In [ ]:
# ===== EXPORT INSIGHTS TO TEXT FILE =====

insight_path = "/content/drive/MyDrive/GColab/final_insights_summary.txt"

with open(insight_path, "w") as f:
    f.write("===== FINAL INSIGHTS SUMMARY =====\n\n")

    f.write(f"Total cleaned rows: {len(combined_df)}\n")
    f.write(f"Columns: {list(combined_df.columns)}\n\n")

    if "Amount" in combined_df.columns:
        f.write(f"Total Amount: {combined_df['Amount'].sum()}\n")
        f.write(f"Average Amount: {combined_df['Amount'].mean():.2f}\n")
        f.write(f"Highest Amount: {combined_df['Amount'].max()}\n")
        f.write(f"Lowest Amount: {combined_df['Amount'].min()}\n\n")

    if "Category" in combined_df.columns and "Amount" in combined_df.columns:
        category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

        top_category = category_summary.idxmax()
        top_value = category_summary.max()

        low_category = category_summary.idxmin()
        low_value = category_summary.min()

        f.write("Category-wise Summary:\n")
        f.write(str(category_summary))
        f.write("\n\n")

        f.write(f"Top Category: {top_category} ({top_value})\n")
        f.write(f"Lowest Category: {low_category} ({low_value})\n\n")

    if "Source_File" in combined_df.columns and "Amount" in combined_df.columns:
        source_summary = combined_df.groupby("Source_File")["Amount"].sum().sort_values(ascending=False)

        top_source = source_summary.idxmax()
        top_source_value = source_summary.max()

        f.write("Source-wise Summary:\n")
        f.write(str(source_summary))
        f.write("\n\n")

        f.write(f"Top Source File: {top_source} ({top_source_value})\n\n")

    f.write("===== HUMAN STYLE SUMMARY =====\n")
    if "Category" in combined_df.columns and "Amount" in combined_df.columns:
        f.write(f"The dataset contains {len(combined_df)} cleaned records.\n")
        f.write(f"The total amount across all records is {combined_df['Amount'].sum()}.\n")
        f.write(f"The average amount per record is {combined_df['Amount'].mean():.2f}.\n")
        f.write(f"The strongest category is {top_category}, contributing {top_value}.\n")
        f.write(f"The weakest category is {low_category}, contributing {low_value}.\n")
        f.write("This indicates where the data is currently strongest and which category may need more attention.\n")

print("✅ Insights saved to:", insight_path)

✅ Insights saved to: /content/drive/MyDrive/GColab/final_insights_summary.txt

In [ ]:
# ===== EXPORT FINAL REPORT WITH INSIGHTS SHEET =====

output_path = "/content/drive/MyDrive/GColab/final_multi_file_report_with_insights.xlsx"

insights_data = []

# Basic stats
insights_data.append(["Metric", "Value"])
insights_data.append(["Total Cleaned Rows", len(combined_df)])
insights_data.append(["Columns", ", ".join(combined_df.columns)])

if "Amount" in combined_df.columns:
    insights_data.append(["Total Amount", combined_df["Amount"].sum()])
    insights_data.append(["Average Amount", round(combined_df["Amount"].mean(), 2)])
    insights_data.append(["Highest Amount", combined_df["Amount"].max()])
    insights_data.append(["Lowest Amount", combined_df["Amount"].min()])

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

    top_category = category_summary.idxmax()
    top_value = category_summary.max()

    low_category = category_summary.idxmin()
    low_value = category_summary.min()

    insights_data.append(["Top Category", top_category])
    insights_data.append(["Top Category Total", top_value])
    insights_data.append(["Lowest Category", low_category])
    insights_data.append(["Lowest Category Total", low_value])

if "Source_File" in combined_df.columns and "Amount" in combined_df.columns:
    source_summary = combined_df.groupby("Source_File")["Amount"].sum().sort_values(ascending=False)

    top_source = source_summary.idxmax()
    top_source_value = source_summary.max()

    insights_data.append(["Top Source File", top_source])
    insights_data.append(["Top Source Total", top_source_value])

# Human summary lines
human_summary = []
human_summary.append("Human Style Summary")

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    human_summary.append(f"The dataset contains {len(combined_df)} cleaned records.")
    human_summary.append(f"The total amount across all records is {combined_df['Amount'].sum()}.")
    human_summary.append(f"The average amount per record is {combined_df['Amount'].mean():.2f}.")
    human_summary.append(f"The strongest category is {top_category}, contributing {top_value}.")
    human_summary.append(f"The weakest category is {low_category}, contributing {low_value}.")
    human_summary.append("This indicates where the data is currently strongest and which category may need more attention.")

insights_df = pd.DataFrame(insights_data[1:], columns=insights_data[0])
human_summary_df = pd.DataFrame({"Summary": human_summary})

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    combined_df.to_excel(writer, sheet_name="Combined_Data", index=False)

    if "Source_File" in combined_df.columns:
        source_count_summary = combined_df["Source_File"].value_counts().reset_index()
        source_count_summary.columns = ["Source_File", "Row_Count"]
        source_count_summary.to_excel(writer, sheet_name="Source_Summary", index=False)

    if "Category" in combined_df.columns and "Amount" in combined_df.columns:
        category_summary.reset_index().to_excel(writer, sheet_name="Category_Summary", index=False)

    insights_df.to_excel(writer, sheet_name="Key_Insights", index=False)
    human_summary_df.to_excel(writer, sheet_name="Human_Summary", index=False)

print("✅ Final report with insights saved to:", output_path)

✅ Final report with insights saved to: /content/drive/MyDrive/GColab/final_multi_file_report_with_insights.xlsx

In [ ]:
# ===== EXPORT FORMATTED FINAL REPORT =====

import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

output_path = "/content/drive/MyDrive/GColab/final_multi_file_report_formatted.xlsx"

# Prepare insight tables
insights_data = []

insights_data.append(["Metric", "Value"])
insights_data.append(["Total Cleaned Rows", len(combined_df)])
insights_data.append(["Columns", ", ".join(combined_df.columns)])

if "Amount" in combined_df.columns:
    insights_data.append(["Total Amount", combined_df["Amount"].sum()])
    insights_data.append(["Average Amount", round(combined_df["Amount"].mean(), 2)])
    insights_data.append(["Highest Amount", combined_df["Amount"].max()])
    insights_data.append(["Lowest Amount", combined_df["Amount"].min()])

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    category_summary = combined_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)
    top_category = category_summary.idxmax()
    top_value = category_summary.max()
    low_category = category_summary.idxmin()
    low_value = category_summary.min()

    insights_data.append(["Top Category", top_category])
    insights_data.append(["Top Category Total", top_value])
    insights_data.append(["Lowest Category", low_category])
    insights_data.append(["Lowest Category Total", low_value])

if "Source_File" in combined_df.columns and "Amount" in combined_df.columns:
    source_summary = combined_df.groupby("Source_File")["Amount"].sum().sort_values(ascending=False)
    top_source = source_summary.idxmax()
    top_source_value = source_summary.max()

    insights_data.append(["Top Source File", top_source])
    insights_data.append(["Top Source Total", top_source_value])

human_summary = []
human_summary.append("Human Style Summary")

if "Category" in combined_df.columns and "Amount" in combined_df.columns:
    human_summary.append(f"The dataset contains {len(combined_df)} cleaned records.")
    human_summary.append(f"The total amount across all records is {combined_df['Amount'].sum()}.")
    human_summary.append(f"The average amount per record is {combined_df['Amount'].mean():.2f}.")
    human_summary.append(f"The strongest category is {top_category}, contributing {top_value}.")
    human_summary.append(f"The weakest category is {low_category}, contributing {low_value}.")
    human_summary.append("This indicates where the data is currently strongest and which category may need more attention.")

insights_df = pd.DataFrame(insights_data[1:], columns=insights_data[0])
human_summary_df = pd.DataFrame({"Summary": human_summary})

# Write sheets
with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    combined_df.to_excel(writer, sheet_name="Combined_Data", index=False)

    if "Source_File" in combined_df.columns:
        source_count_summary = combined_df["Source_File"].value_counts().reset_index()
        source_count_summary.columns = ["Source_File", "Row_Count"]
        source_count_summary.to_excel(writer, sheet_name="Source_Summary", index=False)

    if "Category" in combined_df.columns and "Amount" in combined_df.columns:
        category_summary.reset_index().to_excel(writer, sheet_name="Category_Summary", index=False)

    insights_df.to_excel(writer, sheet_name="Key_Insights", index=False)
    human_summary_df.to_excel(writer, sheet_name="Human_Summary", index=False)

    # Formatting
    wb = writer.book
    header_fill = PatternFill(fill_type="solid", fgColor="D9EAF7")
    header_font = Font(bold=True)
    center_align = Alignment(vertical="center")

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]

        # Freeze top row
        ws.freeze_panes = "A2"

        # Format header row
        for cell in ws[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = center_align

        # Auto-fit column widths
        for col_cells in ws.columns:
            max_length = 0
            col_letter = get_column_letter(col_cells[0].column)

            for cell in col_cells:
                try:
                    cell_len = len(str(cell.value)) if cell.value is not None else 0
                    if cell_len > max_length:
                        max_length = cell_len
                except:
                    pass

            ws.column_dimensions[col_letter].width = min(max_length + 2, 40)

print("✅ Formatted final report saved to:", output_path)

✅ Formatted final report saved to: /content/drive/MyDrive/GColab/final_multi_file_report_formatted.xlsx